//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppSchool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materias
    {
        public int ID_materias { get; set; }
        public int ID_curso { get; set; }
        public string Profesor { get; set; }
        public string Materia { get; set; }
        public string Horario { get; set; }
        public string Duracion { get; set; }
    
        public virtual Curso Curso { get; set; }
    }
}
